### ISSUE TITLE
!playName crashes bot 

### ISSUE THREAD

**Issue by eslachance** [JhonforgeGaming/Music-Bot#3]
If I'm not in a voice channel, and I do !playName , the bot crashes.

**Comment by ScarlettJFG** [comment]
This is something that even I have an issue with. I am fixing it.

**Comment by bwpikaard** [comment]
Maybe try learning how to do something before assuming it's a bug or a problem. 😛

**Comment by ScarlettJFG** [comment]
your right I was taging it so that when I got home I could work on it.

And I do know how to code. Please do not suggest that I don't again. Not that I can really do anything about it but still It's pretty rude.
